rust: re-introduce host target as otherwise missing crates
This was fixed earlier by ensuring to build host rust as well
part of that toolchain otherwise get errors such as:
error[E0463]: can't find crate for `core`
error[E0463]: can't find crate for `compiler_builtins`