libjpeg: force HAVE_BOOLEAN
to avoid conflicts like:
spksrc/cross/leptonica/work-evansport/install//usr/local/include/jmorecfg.h:263:16: error: expected identifier before numeric constant
make[5]: *** [tif_jpeg.lo] Error 1

Because in other libraries (libtiff and giflib in my case) is TRUE,FALSE defined as constants.
Using HAVE_BOOLEAN forces libjpeg to use it as constants too.

libjpeg is used in "cross/leptonica" (not used in any spk) and "cross/pil" (used in spk/python).
"cross/leptonica" - tested, compile passed
"cross/pil" - tested, compile "spk/python" passed.