Enable rust powerpc-unknown-linux-gnuspe for qoriq (#5879)
* py311, sabnzbd, homeassistant: Enable debug_symbols for qoriq

* py311, sabnzbd, homeassistant: Enable debug_symbols also for x64

* py311: Force compiler LTO optimizations with exceptions
  - NOT when testing all wheels
  - NOT when including debug_info symbols
  - NOT when using PPC arch (fails on qoriq)

* py311+sabnzbd+homeassistant: Enable debug_info symbols for all archs

* rustc: Add RUSTFLAGS environment variable option

* qoriq: Tentatively use additional RUSTFLAGS for arch

* toolchain qoriq-6.2.4: Revert RUSTFLAGS and create standard links

- Removing from RUSTFLAGS target-feature=-hard-float,-spe as unsupported
- Create symbolic links using standard "target triple" naming in order
  to avoid confusion due to the usage from Synology of e500v2 specific

* rust: Add support for powerpc-unknown-linux-gnuspe tier 3 target

* rust: Use RUSTUP_TOOLCHAIN env variable to define used toolchain

* rust: Fix default toolchain checking

* duplicity: Update bcrypt wheel from version 4.0.1 to 4.1.1

* py310-py311: Update bcrypt wheel from version 4.0.1 to 4.1.1

* homeassistant: Update bcrypt 4.1.1 and cryptography 41.0.3

* rust: Enforce using newer native/cmake when building toolchain

* rust: Fix typo when building native/cmake

* rust: Tentative to fix online issue relatively to cmake

* rust: Different approach to enforce using native/cmake

* rust: Enforcing --sysroot at link time for tier-3 toolchain builds

* rust: Enforce sysroot using extra RUSTFLAGS variable

* rust: Downgrade to stage1 level compiler and disable toolkit

* rust: Rename custom toolchain to match RUSTUP_TOOLCHAIN for clarity

* rust: Revert back at using stage2 compiler as it fails online

* rust: Clean-up stage0 and stage1 after building stage2

* rust: Add ADDITIONAL_RUSTFLAGS to target-tripple rustflags env var

* rust.mk: Use RUSTUP_TOOLCHAIN overriding +stable|$(toolchain)

* rust: First working version for powerpc-*-gnuspe for qoriq arch

NOTE: requires clean-up and review of every extra variable set

* rust: Removed unused build flags

* rust: Enforce deleting config.toml prior to setting up compiler

* rust: Either use native/llvm-9.0 or include clang-llvm to docker

* rust: Attempt at fixing LLVM error on github-action

* rust: Fix typo in precedent commit

* rust: Remove previous LLVM attempts

* rust: Add llvm-13 and clang-13 part of the base install

* rust: Revert commit related to llvm-13 and clang-13 in Dockerfile

* rust: Enforce build to x86_64-unknown-linux-gnu

* rust: Revert enforcing build triplet

* rust: Disable download-ci-llvm to enforce building of LLVM

* rust: Don't enforce building x86_64 and remove llvm to use default

* rust: Enforce building LLVM

* rust: tentative typo fixing for llvm building

* rust: Change default stage to 2

Hoping to solve github-action error message:
failed: x.py should be run with `--stage 2` on CI, but was run with `--stage 1`

* rust: Re-try downloading LLVM using if-unchanged option

* rust: llvm "if-unchanged" seem to reuquire quotes

* rust: re-introduce host target as otherwise missing crates

This was fixed earlier by ensuring to build host rust as well
part of that toolchain otherwise get errors such as:
error[E0463]: can't find crate for `core`
error[E0463]: can't find crate for `compiler_builtins`

* rust: Specify RUSTUP_TOOLCHAIN so python wheel can build

* native/rust-qoriq: Ability to download and use pre-built toolchain

* rust: Enable usage of native/rust-qoriq

* rust: Fix toolchain setting-up dues to TC_ARCH vs ARCH usages

* rust: "ARCH" detection for toolchain independantly from location

When called from cross or spk usage of $(ARCH)
When called from toolchain:
   - Usage of $(TC_ARCH) when $(TC_NAME) does not exist
   - Usage of $(TC_NAME) for generic archs

* python311: Remove duplicate code kept from rebasing

* homeassistant: Disable GCC_DEBUG_INFO

* python311: Disable GCC_DEBUG_INFO

* sabnzbd: Disable GCC_DEBUG_INFO

* qoriq-6.2.4: convert test to -L and using ln -sf (@hgy59)

* rust: Enable RUST_BUILD_TOOLCHAIN=1 to test rebuild still works

* python311: Fix typo relatively to failure on old ppc only

* tc-rust.mk: Removing left-over exit 2 for debugging purpose

* rust-qoriq: Disable toolchain testing building in favor of native